services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel12-app
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/99-custom.ini:ro
    depends_on:
      - db

  web:
    image: nginx:1.27-alpine
    container_name: laravel12-web
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.0
    container_name: laravel12-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "33060:3306"
    volumes:
      - dbdata:/var/lib/mysql

  node:
    image: node:20-alpine
    container_name: laravel12-node
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

volumes:
  dbdata:
